### ISSUE TITLE
AUR Package was removed and Git package is flagged out of date 

### ISSUE THREAD

**Issue by Techman69** [albfan/aur-miraclecast#4]

**Comment by albfan** [comment]
Changes needed are https://aur.archlinux.org/packages/miraclecast-git#comment-836589

PR welcome!

**Comment by Techman69** [comment]
OK so do I need to submit a PR with the changes in the comment but to close this issue I need The aur package reinstated

**Comment by albfan** [comment]
I don't know if I can help on reinstantiated anything. Probably you need to open an issue somemwehere else

**Comment by Techman69** [comment]
So before filing the issue do I have to do the pr

**Comment by albfan** [comment]
I think all changes needed are already implemented

https://aur.archlinux.org/cgit/aur.git/log/?h=miraclecast-git

What exactly do you miss?

**Comment by Techman69** [comment]
Oh sorry I thought something was missing where should I make am issue I also believe you should try to reinstate the package
